name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: HRKU-7a78efb9-9f12-4c42-a126-0ee9379cca81
          heroku_app_name: msjoa728hh
          heroku_email: heruko0202@gmail.com
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
