name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: HRKU-959f0c75-6ba3-4660-89a5-4662467e2f96
          heroku_app_name: green575dgj
          heroku_email: erichcodes+002@gmail.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
