name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: HRKU-4c925fd6-1a7b-4189-85af-4deaad0ce13c
          heroku_app_name: brazz628hdj
          heroku_email: kristiantiedeman587+hkga8@outlook.com
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
