name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ububtu-22.04
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: HRKU-7d2108c5-1834-4062-8b00-e7eed99ece6c
          heroku_app_name: msjoa878h
          heroku_email: chanchalverma3645@outlook.com
          team: levi
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
