name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: HRKU-c3d329f1-9eb0-449e-8388-7f1adfa9eb58
          heroku_app_name: subha8192
          heroku_email: animesace0@gmail.com
          team: testm594fd
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
