name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: "HRKU-a63732f8-c91e-4d30-a389-ff2485f8852f"
          heroku_app_name: "msjoa879s"
          heroku_email: "heruko0202@gmail.com"
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
