name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: HRKU-4129d621-87a6-4d23-9458-a082c4633cd9
          heroku_app_name: ocean685gjv
          heroku_email: jordansantos7463+t5jls@outlook.com
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
