name: Manually Deploy TEAM WEB EU

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: HRKU-a63732f8-c91e-4d30-a389-ff2485f8852f
          heroku_app_name: mega565gjh
          heroku_email: heruko0202@gmail.com
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
